Added test for validating marriage event selection page
opencrvs/opencrvs-testland pull request #1003
Opened 2024-05-16 04:44 UTC by Eezi

2024-05-23 10:56 UTC, jamil314 requested changes
Branch name needs to be `e2e/marriage` for e2e workflows to trigger

2024-05-23 10:56 UTC, jamil314 commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +      await expect(page.locator('#select_birth_event')).toBeVisible()
User-facing attributes like `label` or `text` should be preferred over css selectors when possible
[prefer-user-facing-attributes-to-xpath-or-css-selectors](https://playwright.dev/docs/best-practices#prefer-user-facing-attributes-to-xpath-or-css-selectors)

2024-05-23 10:56 UTC, jamil314 commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +  test('Testcase 1 Save and exit button', async ({ page }) => {
```suggestion
  test('1.11 Validate save and exit button', async ({ page }) => {
```

2024-05-23 10:56 UTC, jamil314 commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +  test('Testcase 1 Exit button', async ({ page }) => {
```suggestion
  test('1.12 Validate exit button', async ({ page }) => {
```

2024-05-23 10:56 UTC, jamil314 commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +  test('Testcase 1 Three dot menu button', async ({ page }) => {
```suggestion
  test('1.13 Validate three dot menu button', async ({ page }) => {
```

2024-05-23 16:36 UTC, Eezi commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +      await expect(page.locator('#select_birth_event')).toBeVisible()
Nice to know! Should change those id selectors to text or label?

2024-05-24 09:17 UTC, jamil314 commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +      await expect(page.locator('#select_birth_event')).toBeVisible()
Yes, use label / text when possible.

2024-05-27 16:56 UTC, Eezi commented on e2e/testcases/marriage/1-marriage-event-declaration.spec.ts
> +      await expect(page.locator('#select_birth_event')).toBeVisible()
I opened new pr from this and named it correctly so it triggers the e2e workflows and changed all the id selectors to text or label selectors.
Here is the new pr: https://github.com/opencrvs/opencrvs-farajaland/pull/1013

2024-05-28 16:00 UTC, closed without merging