Marriage testcase 7
opencrvs/opencrvs-testland pull request #1024
Opened 2024-06-08 05:09 UTC by Eezi

2024-07-05 09:22 UTC, jamil314 requested changes

2024-07-05 09:22 UTC, jamil314 commented on e2e/testcases/marriage/7-validate-witness-1-page.spec.ts
> +  })
```suggestion
    await goToSection(page, 'witnessOne')
```

2024-07-09 14:22 UTC, jamil314 commented on e2e/testcases/marriage/7-validate-witness-1-page.spec.ts
> +    goToSection(page, 'witnessOne')
```suggestion
    await goToSection(page, 'witnessOne')
```

2024-07-18 06:37 UTC, jamil314 approved these changes

2024-07-27 09:46 UTC, jamil314 requested changes

2024-07-27 09:46 UTC, jamil314 commented on e2e/testcases/marriage/7-validate-witness-1-page.spec.ts
> +
`test.beforeEach` should end here

2024-07-29 07:01 UTC, Eezi commented on e2e/testcases/marriage/7-validate-witness-1-page.spec.ts
> +
Glad you noticed this!👌🏼

2024-07-29 08:17 UTC, jamil314 approved these changes

2024-07-29 08:18 UTC, merged