Ocrvs 6830 human name constant
opencrvs/opencrvs-testland pull request #1164
Opened 2024-11-15 07:34 UTC by Siyasanga

Fix e2e tests after introducing a way to allow countries to customise the order of a full name. turns out there were alot of other screens that use a full name so the changes to the `formatName()` broke a lot of e2e tests. Instead of fixing the tests we've put temporary logic `fullNameWithFirstNameFirst()` helper function which will get removed once all the screens use the `formatName()` function.

https://github.com/opencrvs/opencrvs-core/issues/6830

2025-01-21 13:13 UTC, Zangetsu101 requested changes

2025-01-21 13:13 UTC, Zangetsu101 commented on CHANGELOG.md
> +- Allow countries to customise the format of the full name in the sytem for `sytem users` and `citizens` e.g `{LastName} {MiddleName} {Firstname}`, in any case where one of the name is not provided e
we seems to have duplicate entries here

2025-01-27 14:14 UTC, Siyasanga commented
@Zangetsu101 can you please approve these changes as well to go in with the core changes

2025-01-27 14:19 UTC, Zangetsu101 commented
@Siyasanga we can close this PR as we'll need to use the sync fork button to pull the changes from countryconfig

2025-01-27 14:23 UTC, closed without merging

2025-01-27 14:24 UTC, Siyasanga commented
As per the process, we don't need to merge these changes, we'll pull them from country-config instead