Send registration confirmations to OpenHIM, not directly to workflow
opencrvs/opencrvs-testland pull request #320
Opened 2022-07-25 12:23 UTC by rikukissa

2022-07-26 06:39 UTC, Zangetsu101 requested changes
https://github.com/opencrvs/opencrvs-farajaland/blob/05fa59cc6f5aada3be9893837a0186ace08558cf/src/constants.ts#L40 This also needs to be changed.

2022-07-28 05:52 UTC, Zangetsu101 requested changes

2022-07-28 05:52 UTC, Zangetsu101 commented on src/constants.ts
> +  'http://openhim-core:5001/confirm/registration'
```suggestion
  'http://localhost:5001/confirm/registration'
```
I reckon we need it to be `localhost` for dev

2022-07-28 15:46 UTC, euanmillar requested changes
@rikukissa  If this PR depends upon this Core PR: https://github.com/opencrvs/opencrvs-core/pull/3678 then the then the openhim-dev.gz backup must be regenerated with the new base config imported in this PR.

2022-08-02 09:23 UTC, euanmillar commented
FYI @rikukissa I will do this as I need to regenerate the backup for application config too

2022-08-19 09:30 UTC, merged