Nobody is assigned to any of the declarations generated by the data generator  || Orcvs 3684
opencrvs/opencrvs-testland pull request #340
Opened 2022-09-08 23:23 UTC by modupeadeonojobi

This command "REGISTER=false CERTIFY=false yarn data-generator" assign declarations to nobody while "yarn data-generator" assign declarations to Kennedy Mweene.
<img width="935" alt="fara-dg" src="https://user-images.githubusercontent.com/66411673/189242510-d957b6c7-646f-4405-958d-a270e58621a2.png">

2022-09-09 14:45 UTC, rikukissa approved these changes
👍

2022-09-12 06:28 UTC, Zangetsu101 requested changes
The changes need to be made on `deathDeclarationWorkflow` as well

2022-09-12 06:28 UTC, Zangetsu101 commented on src/data-generator/index.ts
> +        if (REGISTER && CERTIFY) {
If someone wants to proceed till `CERTIFY` i.e. only uses `CERTIFY=false` then the declaration will not be downloaded from here and down the line when trying to reject the declaration, it should throw an error as the declaration was not downloaded.

2022-09-12 06:28 UTC, Zangetsu101 commented on src/data-generator/index.ts
> +            ) {
The declaration is still being downloaded even if `CERTIFY` is false

2022-09-29 10:40 UTC, Zangetsu101 commented
Closing in favor of #356

2022-09-29 10:40 UTC, closed without merging