add dci-crvs-api to docker compose demo deploy
opencrvs/opencrvs-testland pull request #725
Opened 2023-09-26 13:07 UTC by naftis

2023-10-03 09:11 UTC, Zangetsu101 requested changes

2023-10-03 09:11 UTC, Zangetsu101 commented on infrastructure/docker-compose.dci.yml
> +        tag: 'countryconfig'
```suggestion
        tag: 'dci'
```

2023-10-24 07:51 UTC, naftis commented
This is a work in progress until I have a chance to deploy it to an environment, and remove the deployment from staging and see if the example is fine to be under the file it's currently at.

2024-03-05 15:47 UTC, rikukissa commented
@naftis reopen the PR if it's still valid

2024-03-05 15:47 UTC, closed without merging